name: SJRedeem
main: cc.isotopestudio.SJRedeem.sjredeem.SJRedeem

author: Mars
description: Redeem Code with Items
website: http://isotopestudio.cc
version: 1.0.1
commands:
  sd:
    description: 兑换
    usage: /<command> help
  sda:
    description: 兑换
    usage: /<command> help